laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\User;
use App\Post;
use App\Category;
use App\Http\Resources\UserResource;
use App\Http\Resources\PostResource;

Route::resource('/category', 'CategoryController');
Route::resource('/user_detail','UserDetailController');
Route::resource('/post','PostController');
Route::get('/','PostController@index');
Route::get('/my_post','PostController@myPost');

//ajax routes
Route::post('/post/filter', 'PostController@getFilterPost')->name('post.filter');


Route::get('/home', 'HomeController@index')->name('home');
Auth::routes();
Route::get('/json',function(){
  return new PostResource(Post::all());
});

laravel/app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //model name will always be singular
    protected $table = 'categories';
    protected $fillable = [
        'name'
    ];

    public function posts(){
        return $this->hasMany(Post::class, 'category_id', 'id');
    }
}

laravel/app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;
use App\Post;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;


class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        return view('categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validator($request->all())->validate();
        Category::create([
           'name'   =>  $request->category_name
        ]);
        return redirect()->route('category.index')->with('msg', 'Category has been created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::findOrFail($id);
        return view('categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validator( $request->all())->validate();
        $category = Category::findOrFail($id);
        $category->update([
            'name' => $request->category_name
        ]);
        return redirect()->route('category.index')->with('msg', 'Category Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::findOrFail($id);
        $category->delete();
        return redirect()->route('category.index')->with('msg','Category has been deleted');

    }

    public function validator( array $data ){
        return validator::make( $data, [
            'category_name' => 'required|string|max:191'
        ] );
    }
}

laravel/resources/views/categories/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{__('Create Post')}}</div>
                <div class="card-body">
                    <form action="{{ route('category.store') }}" method="post">
                        @csrf
                        <div class="form-group">
                            <label>Category</label>
                            <input class="form-control" name="category_name" type="text">
                        </div>
                        <button>Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

laravel/resources/views/categories/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{__('Edit Category')}}</div>
                <div class="card-body">
                    <form action="{{ route('category.update', $category->id) }}" method="post">
                        @csrf
                        {{ method_field('PUT') }}
                        <div class="form-group">
                            <label>Category</label>
                            <input class="form-control" name="category_name" type="text" value="{{ $category->name }}">
                        </div>
                        <button>Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

laravel/resources/views/categories/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{__('Edit Category')}}</div>
                <div class="card-body">
                    @if(!empty($categories))
                        <table class="table table-hover">
                            <thead>
                                <th>Id</th>
                                <th>Name</th>
                                <th>Edit</th>
                                <th>Delete</th>
                            </thead>
                            <tbody>
                                @foreach($categories as $category)
                                    <tr>
                                        <td>{{$category->id}}</td>
                                        <td>{{$category->name}}</td>
                                        <td><a class="btn btn-sm btn-success" href="{{ route('category.edit', $category->id) }}">Edit</a></td>
                                        <td>
                                            <form action="{{ route('category.destroy', $category->id) }}" method="post">
                                                @csrf
                                                {{ method_field('DELETE') }}
                                                <button class="btn btn-sm btn-danger">Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    @else
                        Nothing found
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection