laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\User;
use App\Post;
use App\Category;
use App\Http\Resources\UserResource;
use App\Http\Resources\PostResource;

Route::resource('/category', 'CategoryController');
Route::resource('/user_detail','UserDetailController');
Route::resource('/post','PostController');
Route::get('/','PostController@index');
Route::get('/my_post','PostController@myPost');

//ajax routes
Route::post('/post/filter', 'PostController@getFilterPost')->name('post.filter');


Route::get('/home', 'HomeController@index')->name('home');
Auth::routes();
Route::get('/json',function(){
  return new PostResource(Post::all());
});

laravel/app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $table = 'posts';
    protected $fillable = [
        'user_detail_id', 'category_id', 'title', 'image', 'content'
    ];

    public function category(){
        return $this->belongsTo(Category::class,'category_id','id');
    }

    public function user_detail(){
        return $this->belongsTo(UserDetail::class, 'user_detail_id', 'id');
    }  
    
    public function getShortContentAttribute()
    {
        return substr($this->content, random_int(0,100)) . '...';
    }
}

laravel/app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\UserDetail;
use Illuminate\Http\Request;
use App\Post;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;


class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        $posts = Post::with('user_detail')->orderBy('created_at','desc')->paginate(9);
        return view('posts.post', compact('categories','posts'));
    }

    /** 
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('posts.create_post', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'title'=>'required',
            'image'=>'mimes:png,jpg,svg,jpeg',
            'content'=>'required',
            ]);

        //uploading the image locally in the folder, you can change it
            $imageName = null;
            if( $request->hasFile('image')){
                $imageName = $request->file('image')->getClientOriginalName();
                //concating the image name with time-stamp so every-image have unique name in folder
                $imageName = time().'_'.$imageName;

                $path = Storage::disk('public')->putFileAs(
                    'avatars', $request->file('image'), $imageName
                );
            }

        Post::create([
           'user_detail_id' => Auth()->user()->id,
            'category_id'   => $request->category_id,
            'title'         => $request->title,
            'image'         => $imageName,
            'content'       => $request->content
        ]);

        return redirect('/')->with('msg', 'Post has been added.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $categories = Category::all();
        //use find or fail because if it does not id it will make an exception 
        //and doesnot exceute code further
        $post = Post::findOrFail($id);
        //getting with relationship
        $user_detail = $post->user_detail;
        // $user_detail = UserDetail::findOrFail($id);
        if(Auth::guest())
        {
            return view('posts.post_details_guest', compact('categories','post','user_detail'));
        }
        else
        {
            return view('posts.post_details', compact('categories','post','user_detail'));
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // $categories = Category::all();
        $cats = Category::all();
        $post = Post::findOrFail($id);
        if($post->user_detail->user_id == Auth()->user()->id){
            return view('posts.edit_post', compact('post','cats'));
        }else{
            return redirect()->back()->with('msg', 'You can not edit this post');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'title'=>'required',
            'image'=> 'mimes:png,jpg,svg,jpeg',
            'content'=>'required',
            ]);

        $post = Post::findOrFail($id);
        if($post->user_detail->user_id == auth()->user()->id){
            //uploading the image locally in the folder, you can change it
                
                if( $request->hasFile('image')){
                    $imageName = $request->file('image')->getClientOriginalName();
                    //concating the image name with time-stamp so every-image have unique name in folder
                    $imageName = time().'_'.$imageName;

                    $path = Storage::disk('public')->putFileAs(
                        'avatars', $request->file('image'), $imageName
                    );
                }else{
                    $imageName = $post->image;
                }

            //in case you pass category name from form then
            // $category = Category::where('name', $request->category_name)->get();   
            // $cat_id = $category->id; 

            $post->update([
            'user_detail_id' => Auth()->user()->id,
                'category_id'   => $request->category_id,
                'title'         => $request->title,
                'image'         => $imageName,
                'content'       => $request->content
            ]);

            return redirect('/')->with('msg', 'Product has been Updated.');
        }else{
            return back()->with('msg', 'You can not edit this post.');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::findOrFail($id);
        $post->delete();
        return redirect()->route('post.index')->with('msg', 'Post has been deleted.');
    }

    public function getFilterPost(Request $request){
        $cat_id = $request->category_id;
        if($cat_id == 0){
            $posts = Post::all();
            if(!empty($posts)){
                return response()->json(['data'=>$posts, 'status'=>'success']);
            }else{
                return response()->json(['status'=>'fail']);
            }
        }else{
            $posts = Post::with('category')->where('category_id', $cat_id)->get();
            if(!empty($posts)){
                return response()->json(['data'=>$posts, 'status'=>'success']);
            }else{
                return response()->json(['status'=>'fail']);
            }
        }
        
    }
    public function myPost()
    {
        // $categories = Category::all();
        // $posts = \DB::table('posts')
        //                             ->join('user_details', 'posts.user_detail_id', '=', 'user_details.id')
        //                             ->join('users','users.id','=', 'user_details.user_id')
        //                             ->select('posts.*','user_details.*')
        //                             ->get();
        $posts = Post::with('user_detail')->orderBy('created_at','desc')->get();
        return view('posts.my_post', compact('posts'));
    }
}

laravel/resources/views/posts/create_post.blade.php
@extends('layouts.app')
@section('content')
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">{{__('Create Post')}}</div>
        <div class="card-body">
          {!! Form::open(['action' => 'PostController@store', 'method' => 'POST', 'files'=> true, 'enctype' => 'multipart/form-data']) !!}

            <div class="form-group">
              {{ Form::label('cat_name','Choose Category') }}
              <select class="form-control" name="category_id" id="">
                  @if(!empty($categories))
                      @foreach($categories as $cat)
                          <option @if($cat->name == 'All') disabled @endif value={{$cat->id}}>{{$cat->name}}</option>
                      @endforeach
                  @endif
              </select>
            </div>

            <div class="form-group">
              {{ Form::label('title','Title') }}
              {{ Form::text('title','',['class'=>'form-control']) }}
            </div>

            <div class="form-group">
              {{ Form::label('image',' Image') }}
              {{ Form::file('image',['class'=>'form-control']) }}
            </div>

            <div class="form-group">
              {{ Form::label('content','Content') }}
              {{ Form::textArea('content','',['id' => 'article-ckeditor','class'=>'form-control']) }}
            </div>

            {!! Form::submit('Post',['class'=>'btn btn-primary']) !!}

          {!! Form::close() !!}
        </div>  
      </div>
    </div>
  </div>
@endsection

laravel/resources/views/posts/edit_post.blade.php
@extends('layouts.app')
@section('content')
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">{{__('Edit Post')}}</div>
        <div class="card-body">
          {!! Form::open(['action' => ['PostController@update', $post->id], 'method' => 'POST', 'files'=> true, 'enctype' => 'multipart/form-data']) !!}

            <div class="form-group">
              {{ Form::label('cat_name','Choose Category') }}
              <select class="form-control" name="category_id" >
                  @foreach($cats as $cat)
                   <option value="{{$cat->id}}" @if($cat->id == $post->category_id) selected @endif>{{$cat->name}}</</option>
                  @endforeach
              </select>
            </div>

            <div class="form-group">
              {{ Form::label('title','Title') }}
              {{ Form::text('title',$post->title,['class'=>'form-control']) }}
            </div>

            <div class="form-group">
              {{ Form::label('image',' Image') }}
              {{ Form::file('image' ,['class'=>'form-control']) }}
            </div>

            <div class="form-group">
              {{ Form::label('content','Content') }}
              {{ Form::textArea('content',$post->content,['id' => 'article-ckeditor','class'=>'form-control']) }}
            </div>
            {!! Form::hidden('_method','PUT')!!}
            {!! Form::submit('Update',['class'=>'btn btn-primary']) !!}
            <a style="float: right" class="btn btn-primary" href="/">Back</a>
          {!! Form::close() !!}
        </div>  
      </div>
    </div>
  </div>
@endsection

laravel/resources/views/posts/my_post.blade.php
@extends('layouts.app')
@section('content')

    <!-- Card Narrower -->
    <br><br><br>
    <div class="row" id="post-wrapper">
        @if(!empty($posts))
            @foreach($posts as $post)
                @if($post->user_detail_id == auth()->user()->id)
                  <a href="/post/ {{ $post->id }}">
                      <div class="col-md-4" style="margin-top: 20px;">
                          <div class="card card-cascade narrower">

                              <!-- Card image -->
                              <div class="view view-cascade overlay">
                                  <img style="height:300px" class="card-img-top" src="{{ Storage::url('avatars/'.$post->image) }}"
                                      alt="Card image cap">
                                  <a>
                                      <div class="mask rgba-white-slight"></div>
                                  </a>
                              </div>

                              <!-- Card content -->
                              <div class="card-body card-body-cascade">
                                  <h4 style="text-align: center;" class="font-weight-bold card-title">{{$post->title}}</h4>
                              </div>
                          </div>
                      </div>
                  </a>
                @endif
            @endforeach
        @endif

    </div>
    <!-- Card Narrower -->

@endsection

laravel/resources/views/posts/post.blade.php
@extends('layouts.app')
@section('content')

    <select style="float:right;width: 100px" class="form-control" name="category_id" id="category">
    <!-- for all never store all in database :) -->
        <option value="0">All</option>
        @if(!empty($categories))    
            @foreach($categories as $cat)
                <option value={{$cat->id}}>{{$cat->name}}</option>
            @endforeach
        @endif
    </select>
    <span style="float: right; margin: 8px">sort by:</span>
    <!-- Card Narrower -->
    <br><br><br>
    <div class="row" id="post-wrapper">
        @if(!empty($posts))
            @foreach($posts as $post)
                <a href="/post/ {{ $post->id }}">
                    <div class="col-md-4" style="margin-top: 20px;">
                        <div class="card card-cascade narrower">

                            <!-- Card image -->
                            <div class="view view-cascade overlay">
                                <img style="height:300px" class="card-img-top" src="{{ Storage::url('avatars/'.$post->image) }}"
                                    alt="Card image cap">
                                <a>
                                    <div class="mask rgba-white-slight"></div>
                                </a>
                            </div>

                            <!-- Card content -->
                            <div class="card-body card-body-cascade">

                                <!-- Label -->
                                <h5 class="pink-text pb-2 pt-1"></i>{{$post->shop}}</h5>
                                <!-- Title -->
                                <h4 style="text-align: center;" class="font-weight-bold card-title">{{$post->title}}</h4>
                                <!-- Text -->
                                <!-- <p class="card-text">{!! $post->getShortContentAttribute() !!}</p> -->
                                <!-- Button -->
                            </div>
                        </div>
                    </div>
                </a>
            @endforeach
        @endif



    </div><br>
    <!-- Card Narrower -->
    {{ $posts->links() }}
    <br>

@endsection

@push('js')
    <script>
    $("#category").change( function(){
        //getting the category id
        var category_id = $(this).val();
        //getting the csrf tokken for post request
        var token = $('meta[name=csrf-token]').attr("content");
        $.ajax({
            url : '{{route('post.filter')}}',
            type: 'POST',
            //sending token and category_id in post request
            data: {_token: token, category_id: category_id},
            //send the json response
            dataType: 'JSON',
            //get the response in the data
            success : function(data){
                var posts = '';
                if(data.status == 'success'){
                    $(data.data).each( function(i,d){
                        posts += '<a href="/post/'+ d.id +'">\n' +
                                    '<div class="col-md-4" style="margin-top: 20px;">\n'+
                                        '<div class="card card-cascade narrower">\n'+
                                            '<div class="view view-cascade overlay">\n'+
                                                '<img style="height:300px" class="card-img-top" src="{{Storage::url('avatars/')}}'+ d.image +'"\n'+
                                                   ' alt="Card image cap">\n'+
                                                '<a>\n'+
                                                    '<div class="mask rgba-white-slight"></div>\n'+
                                                '</a>\n'+
                                            '</div>\n'+
                                            '<div class="card-body card-body-cascade">\n'+
                                                '<h5 class="pink-text pb-2 pt-1"><i class="fa fa-cutlery"></i></h5>\n'+
                                                '<h4 style="text-align: center;" class="font-weight-bold card-title">'+ d.title +'</h4>\n'+
                                            '</div>\n'+
                                        '</div>\n'+
                                    '</div>\n'+
                                '</a>';
                    });
                    $("#post-wrapper").html(posts);
                }
                // error: function(data){
                //     if(data.status == 'fail'){
                //         post += '<h3 class="center-text">Sorry No post available against this category.</h3>';
                //         $("#post-wrapper").html(post);
                //     }
                // }
            }
        });
    });
    </script>
@endpush

laravel/resources/views/posts/post_details.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-md-6">
        
            <div class="card card-cascade narrower">

                <!-- Card image -->
                <div class="view view-cascade overlay">
                    <img  class="card-img-top" src="{{ Storage::url('avatars/'.$post->image) }}" alt="Card image cap">
                    <a>
                        <div class="mask rgba-white-slight"></div>
                    </a>
                </div>
            </div>
        </div> 
        <div class="col-md-6">
            <div class="card card-cascade narrower">
                <!-- Card content -->
                <div class="card-body card-body-cascade">
                        <div class="row">
                            <div class="col-md-6">
                                <!-- Title -->
                                <h4 class="font-weight-bold card-title">{{$post->title}}</h4>
                                <!-- Text -->
                                <p class="card-text">{!! $post->content !!}</p>
                                <p class="card-text"><strong>Date: </strong> {{ $post->created_at }}</p> <br>
                            </div>
                            <div class="col-md-6">
                                <h4 class="font-weight-bold card-title">Shop Details</h4>
                                <p class="card-text"><strong>Phone: </strong> {{ $user_detail->phone }}</p>
                                <p class="card-text"><strong>Shop: </strong> {{ $user_detail->shop }}</p>
                                <p class="card-text"><strong>Address: </strong> {{ $user_detail->address }}</p>
                            </div>
                        </div>
                        <br><br>
                        <div class="row">
                            <div class="col-md-6">
                                <a href="/"><button class="btn btn-primary">Back</button></a>
                            </div>
                            <div class="col-md-6">
                                @if( $user_detail->user_id == auth()->user()->id)
                                    <div style="float: right" class="btn-group">
                                        <button class="btn btn-danger dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">More</button>
                                        <div class="dropdown-menu">
                                            <a class="dropdown-item" href="{{ route('post.edit', $post->id) }}">Edit</a>
                                            {!!Form::open(['action' => ['PostController@destroy', $post->id ], 'method' => 'POST'])!!}
                                                {{ Form::hidden('_method','DELETE') }}  
                                                {{ Form::submit('Delete',['class'=>'dropdown-item'])}} 
                                            {!!Form::close()!!}
                                        </div>
                                    </div>  
                                @endif
                            </div>
                            
                        </div>
                    </div>
            </div>
        </div> 
    </div> 

@endsection

laravel/resources/views/posts/post_details_guest.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-md-6">
        
            <div class="card card-cascade narrower">

                <!-- Card image -->
                <div class="view view-cascade overlay">
                    <img  class="card-img-top" src="{{ Storage::url('avatars/'.$post->image) }}" alt="Card image cap">
                    <a>
                        <div class="mask rgba-white-slight"></div>
                    </a>
                </div>
            </div>
        </div> 
        <div class="col-md-6">
            <div class="card card-cascade narrower">
                <!-- Card content -->
                <div class="card-body card-body-cascade">
                        <div class="row">
                            <div class="col-md-6">
                                <!-- Title -->
                                <h4 class="font-weight-bold card-title">{{$post->title}}</h4>
                                <!-- Text -->
                                <p class="card-text">{!! $post->content !!}</p>
                                <p class="card-text"><strong>Date: </strong> {{ $post->created_at }}</p>
                            </div>
                            <div class="col-md-6">
                                <h4 class="font-weight-bold card-title">Shop Details</h4>
                                <p class="card-text"><strong>Phone: </strong> {{ $user_detail->phone }}</p>
                                <p class="card-text"><strong>Shop: </strong> {{ $user_detail->shop }}</p>
                                <p class="card-text"><strong>Address: </strong> {{ $user_detail->address }}</p>
                            </div>
                        </div>
                        <br><br>
                        <div class="row">
                            <div class="col-md-6">
                                <a href="/"><button class="btn btn-primary">Back</button></a>
                            </div>
                        </div>
                    </div>
            </div>
        </div> 
    </div> 

@endsection